spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL:localhost}:${POSTGRES_URL_PORT:5432}/${POSTGRES_DB_NAME:contact-crud}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
        ddl-auto: create

server:
  servlet:
    context-path: /api
  port: ${BACKEND_PORT:8080}